Add Portuguese Language File
otacke/h5p-jigsaw-puzzle pull request #9
Opened 2022-01-25 23:45 UTC by paulofvieira

Translated to Pt Pt

2022-01-25 23:51 UTC, otacke requested changes
Thanks a lot for contributing!

You've included all of semantics.json, however - which is not a translation file. The template would be [.en.json](https://github.com/otacke/h5p-jigsaw-puzzle/blob/master/language/.en.json). You'd have to change that.

If you don't want to run into such a mishap, you could use https://translate-h5p.tk/ which not only prevents such issues, but also has some other nice features like getting messages when there are new translations waiting, etc.

Cheers,
Oliver

2022-01-31 09:51 UTC, otacke requested changes
The file that you have asked to pull now is not valid JSON. There are dangling commas where they don't belong.

I can only repeat myself: You should consider to use https://translate-h5p.tk to translate H5P content types. The issues that I now had to hint to couldn't have happened then and we'd both have had less to do.

2022-01-31 09:51 UTC, otacke commented on language/pt.json
> +          "label": "Possibilita o botão de \"Finalizar\" o puzzle",
invalid JSON format

2022-01-31 09:51 UTC, otacke commented on language/pt.json
> +          "label": "Possibilita o botão de \"Tentar novamente\"",
invalid JSON format

2022-01-31 09:51 UTC, otacke commented on language/pt.json
> +          "label": "Possibilita o botão para mostrar \"Solução\"",
invalid JSON format

2022-02-05 21:29 UTC, paulofvieira commented
ty, i will do as suggested. What is the name of the project on weblate?

2022-02-05 21:35 UTC, otacke commented
It's hosted on https://translate-h5p.tk/ as mentioned before.

2022-03-29 12:02 UTC, merged

2022-03-29 12:02 UTC, otacke commented
Fixed this myself now.